#!/bin/bash

# Filename: ~/.config/sketchybar/sketchybarrc

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh"  # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items"     # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

# Needs to have Regular, Bold, Semibold, Heavy and Black variants
# FONT="SF Pro"
FONT="MesloLGM Nerd Font"

# All paddings use this value (icon, label, background)
PADDINGS=5

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER >/dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

# Setting up the general bar appearance of the bar

sketchybar --bar position=top height=32 color=$TRANSPARENT blur_radius=0
sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  blur_radius=50
  background.drawing=on
  background.color=$BACKGROUND_1
  background.border_width=0
  background.height=26
  background.corner_radius=2
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=50
  popup.background.shadow.drawing=on
  scroll_texts=on
)

sketchybar --default "${defaults[@]}"

###############################################################################
#                                Left side
###############################################################################

# Shows the apple logo, you can change it's color in "items/apple.sh"
# If you click on it, you can see preferences, activity and lock screen
#source "$ITEM_DIR/apple.sh"

# Shows the name and icon of the app currently focused
# Clicking it opens mission control (can be customized)
source "$ITEM_DIR/front_app.sh"


# CPU usage indicator
source "$ITEM_DIR/cpu.sh"

###############################################################################
#                               Right side
###############################################################################

# If calendar is clicked, will run zen.sh which hides everything, but you can
# customize it to your liking
source "$ITEM_DIR/calendar.sh"


# Internet speed
source "$ITEM_DIR/network.sh"

###############################################################################

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
